export const FETCH_CRYPTO_ACTION_TYPES = {
    FETCH_CRYPTO_REQUEST: "FETCH_CRYPTO_REQUEST",
    FETCH_CRYPTO_FULFILLED: "FETCH_CRYPTO_FULFILLED",
    FETCH_CRYPTO_REJECTED: "FETCH_CRYPTO_REJECTED"
};

export const FETCH_MORE_CRYPTO_ACTION_TYPES = {
    FETCH_MORE_CRYPTO_REQUEST: "FETCH_MORE_CRYPTO_REQUEST",
    FETCH_MORE_CRYPTO_FULFILLED: "FETCH_MORE_CRYPTO_FULFILLED",
    FETCH_MORE_CRYPTO_REJECTED: "FETCH_MORE_CRYPTO_REJECTED"
};
